### ISSUE TITLE
explainers-by-googlers LICENSE vs. WICG LICENSE.md

### ISSUE THREAD

**Issue by domenic** [explainers-by-googlers/template#6]
I created an explainer using this template (https://github.com/WICG/translation-api/commit/380e443cf85459ac8f6981bfd204b60bad4331c9). It contained the CC-BY-4.0 `LICENSE` file

As part of moving to WICG, in https://github.com/WICG/translation-api/commit/543bb116ee06c3c9188001e938621c92b88a0b06 @cwilso added a `LICENSE.md` explaining that the W3C Software and Document License applies.

Now I have two licenses. I'm going to delete `LICENSE`. But, it would be good if we avoided this situation in the future.

Maybe one easy way of doing that would be to change our LICENSE to a LICENSE.md, so that the conflict is easily detected.

**Comment by jyasskin** [comment]
That sounds good to me. Want to send a PR?
